export const test = [
  ['gen', 'genesis'],
  ['ex', 'exodus'],
  ['lev', 'leviticus'],
  ['num', 'numbers'],
  ['deut', 'deuteronomy'],
  ['josh', 'joshua'],
  ['judg', 'judges'],
  ['ruth', 'ruth'],
  ['1 sam', '1 samuel'],
  ['2 sam', '2 samuel'],
  ['1 kgs', '1 kings'],
  ['2 kgs', '2 kings'],
  ['1 chr', '1 chronicles'],
  ['2 chr', '2 chronicles'],
  ['ezra', 'ezra'],
  ['neh', 'nehemiah'],
  ['esth', 'esther'],
  ['job', 'job'],
  ['ps', 'psalms'],
  ['prov', 'proverbs'],
  ['eccl', 'ecclesiastes'],
  ['song', 'song of solomon'],
  ['isa', 'isaiah'],
  ['jer', 'jeremiah'],
  ['lam', 'lamentations'],
  ['ezek', 'ezekiel'],
  ['dan', 'daniel'],
  ['hosea', 'hosea'],
  ['joel', 'joel'],
  ['amos', 'amos'],
  ['obad', 'obadiah'],
  ['jonah', 'jonah'],
  ['micah', 'micah'],
  ['nahum', 'nahum'],
  ['hab', 'habakkuk'],
  ['zeph', 'zephaniah'],
  ['hag', 'haggai'],
  ['zech', 'zechariah'],
  ['mal', 'malachi'],
  ['matt.', 'matthew'],
  ['mark', 'mark'],
  ['luke', 'luke'],
  ['john', 'john'],
  ['acts', 'acts'],
  ['rom.', 'romans'],
  ['1 cor.', '1 corinthians'],
  ['2 cor.', '2 corinthians'],
  ['gal.', 'galatians'],
  ['eph.', 'ephesians'],
  ['philip.', 'philippians'],
  ['col.', 'colossians'],
  ['1 thes.', '1 thessalonians'],
  ['2 thes.', '2 thessalonians'],
  ['1 tim.', '1 timothy'],
  ['2 tim.', '2 timothy'],
  ['titus', 'titus'],
  ['philem.', 'philemon'],
  ['heb.', 'hebrews'],
  ['james', 'james'],
  ['1 pet.', '1 peter'],
  ['2 pet.', '2 peter'],
  ['1 jn.', '1 john'],
  ['2 jn.', '2 john'],
  ['3 jn.', '3 john'],
  ['jude', 'jude'],
  ['rev.', 'revelation'],
  ['gen.', 'genesis'],
  ['ex.', 'exodus'],
  ['lev.', 'leviticus'],
  ['num.', 'numbers'],
  ['deut.', 'deuteronomy'],
  ['josh.', 'joshua'],
  ['judg.', 'judges'],
  ['ruth', 'ruth'],
  ['1 sam.', '1 samuel'],
  ['2 sam.', '2 samuel'],
  ['1 kgs.', '1 kings'],
  ['2 kgs.', '2 kings'],
  ['1 chr.', '1 chronicles'],
  ['2 chr.', '2 chronicles'],
  ['ezra', 'ezra'],
  ['neh.', 'nehemiah'],
  ['esth.', 'esther'],
  ['job', 'job'],
  ['ps.', 'psalms'],
  ['prov.', 'proverbs'],
  ['eccl.', 'ecclesiastes'],
  ['song', 'song of solomon'],
  ['isa.', 'isaiah'],
  ['jer.', 'jeremiah'],
  ['lam.', 'lamentations'],
  ['ezek.', 'ezekiel'],
  ['dan.', 'daniel'],
  ['hosea', 'hosea'],
  ['joel', 'joel'],
  ['amos', 'amos'],
  ['obad.', 'obadiah'],
  ['jonah', 'jonah'],
  ['micah', 'micah'],
  ['nahum', 'nahum'],
  ['hab.', 'habakkuk'],
  ['zeph.', 'zephaniah'],
  ['hag.', 'haggai'],
  ['zech.', 'zechariah'],
  ['mal.', 'malachi'],
  ['1 ne.', '1 nephi'],
  ['2 ne.', '2 nephi'],
  ['jacob', 'jacob'],
  ['enos', 'enos'],
  ['jarom', 'jarom'],
  ['omni', 'omni'],
  ['w of m', 'words of mormon'],
  ['mosiah', 'mosiah'],
  ['alma', 'alma'],
  ['hel.', 'helaman'],
  ['3 ne.', '3 nephi'],
  ['4 ne.', '4 nephi'],
  ['morm.', 'mormon'],
  ['ether', 'ether'],
  ['moro.', 'moroni'],
  ['d&c', 'doctrine and covenants'],
  ['od', 'official declaration'],
  ['moses', 'moses'],
  ['abr.', 'abraham'],
  ['js—m', 'joseph smith—matthew'],
  ['js—h', 'joseph smith—history'],
  ['a of f', 'articles of faith'],
  ['jst', 'joseph smith translation'],
  ['tg', 'topical guide'],
  ['bd', 'bible dictionary'],
  ['it', 'index to the triple combination'],
  ['gs', 'guide to the scriptures'],
];
